language: ruby
rvm:
  - 2.6.4
#sudo: false

cache: bundler

branches:
  only:
  - master

script:
  - scripts/build.sh

deploy:
  provider: script
  skip-cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: release